## Cluster Settings
cluster.name: "docker-cluster"

## Node Settings
node.name: "node-1"
# Node role can be defined explicitly for more complex setups. For a single-node or basic setup, this is not strictly necessary.

## Path Settings
path.data: /usr/share/elasticsearch/data
path.logs: /var/log/elasticsearch

## Network Settings
network.host: 0.0.0.0 # Binds Elasticsearch to all host interfaces. Adjust this for production environments.
http.port: 9200

## Discovery Settings
# For a single-node setup, like in many Docker environments, discovery is simplified:
discovery.type: single-node

## Security Settings
# Starting with Elasticsearch 7.x, security features are available by default in the Basic license.
#xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: false # For internal cluster communication, consider enabling SSL in production
# HTTP SSL/TLS settings for REST API
#xpack.security.http.ssl.enabled: false # Consider enabling and configuring SSL for HTTP in production

## Additional Settings
# These are placeholders for any additional custom settings you might need:
# e.g., custom plugins, integrations, etc.


