name: Docker-Image-Python-Worker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the python worker image
      run: docker buildx build python-worker/. -t python-worker 
